version: 2
jobs:

  test:
    docker:
      - image: 'circleci/node:10.16'
    steps:
      - checkout
      - restore_cache:
          key: lookingatyou-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: lookingatyou-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm run test

  deploy:
    docker:
      - image: 'circleci/python:3.6.4-stretch'
    steps:
      - checkout
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: sudo apt-get -y install curl
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run:
          name: Install Node.js and npm
          command: sudo apt-get -y install nodejs
      - run: npm --version
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: "Deploy to S3"
          command: aws s3 sync ./build/ s3://looking-at-you/ --delete

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
